### PR TITLE
Maintaining consistency in checking type of object

### PR DESCRIPTION
**Pull request by abhaystoic**

### CODE REVIEW

**Comment by fzumstein** [comment]
Was there anything you noted in functionality or is it purely stylistic?

**Comment by abhaystoic** [comment]
It's purely stylistic.

**Comment by fzumstein** [comment]
ok we're still trying to find out if it was actually done on purpose the way it was done. I ll leave it open for the moment, also you seem to have opened the PR twice so I ll close the other one.

**Comment by jmikovic** [comment]
Hi, what is the status of this PR?
There's a functionality issue this solves as the tool doesn't work with subclasses of dict such as OrderedDict

**Pull request merged**
